{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alpine-tor.serviceAccountName" . }}
  labels:
{{ include "alpine-tor.labels" . | nindent 4 }}
{{- end -}}
