kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "alpine-tor.fullname" . }}-volume
  labels:
    type: local
spec:
  capacity:
    storage: 100M
  storageClassName: alpine-tor-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mountpath }}
