apiVersion: v1
kind: Service
metadata:
  name: alpine-tor-bridge-service
  labels:
    deploy: alpine-tor-bridge
spec:
  type: NodePort 
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: orport
  selector:
    deploy: alpine-tor-bridge
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alpine-tor-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: alpine-tor-bridge
  template:
    metadata:
      labels:
        deploy: alpine-tor-bridge
    spec:
      containers:
        - name: alpine-tor-bridge
          image: jfwenisch/alpine-tor
          env:
          - name: mode
            value: bridge