apiVersion: v1
kind: Service
metadata:
  name: alpine-tor-exit-service
  labels:
    deploy: alpine-tor-exit
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: dirservicePort
  selector:
    deploy: alpine-tor-exit
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alpine-tor-exit
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: alpine-tor-exit
  template:
    metadata:
      labels:
        deploy: alpine-tor-exit
    spec:
      containers:
        - name: alpine-tor-exit
          image: jfwenisch/alpine-tor
          env:
          - name: mode
            value: exit