apiVersion: v1
kind: Service
metadata:
  name: alpine-tor-proxy-service
  labels:
    deploy: alpine-tor-proxy
spec:
  type: NodePort 
  ports:
  - port: 9050
    targetPort: 9050
    protocol: TCP
    name: socks5
  selector:
    deploy: alpine-tor-proxy
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alpine-tor-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: alpine-tor-proxy
  template:
    metadata:
      labels:
        deploy: alpine-tor-proxy
    spec:
      containers:
        - name: alpine-tor-proxy
          image: jfwenisch/alpine-tor
          env:
          - name: mode
            value: proxy