apiVersion: v1
kind: Service
metadata:
  name: alpine-tor-service
  labels:
    deploy: alpine-tor
spec:
  type: NodePort 
  ports:
  - port: 9050
    targetPort: 9050
    protocol: TCP
    name: socks5
  selector:
    deploy: alpine-tor
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alpine-tor
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 2. How do want to update the pods?
  #strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: alpine-tor
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: alpine-tor
    spec:
      containers:
        - name: alpine-tor
          image: jfwenisch/alpine-tor